console.log(Math);
console.log(Math.abs(-4));
console.log(Math.abs(7));
console.log(Math.round(5.7));
console.log(Math.ceil(5.1));
console.log(Math.floor(6.8));
console.log(Math.sqrt(60));
console.log(Math.sin(1));
console.log(Math.min(10, 6, 7, 8));
console.log(Math.max(10, 6, 7, 8));
console.log(Math.floor(Math.random() * 10));
const min = 10;
const max = 5000;
console.log(Math.floor(Math.random() * (max - min + 1)) + max);
